name: playstack
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.9
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3
  provider: ^4.0.4
  flutter_spinkit: "^4.1.2"
  path_provider: ^1.2.0
  flutter_exoplayer: ^0.5.5
  audioplayers: ^0.14.2
  dio: ^3.0.9
  image_picker: ^0.6.5
  mime: ^0.9.6+3
  bot_toast: ^2.4.0
  toast: ^0.1.5
  url_launcher: ^5.1.3
  flutter_form_bloc: ^0.14.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5
flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - google-fonts/
    - lib/assets/Photos/logo.png
    - lib/assets/Photos/logo_name.png
    - lib/assets/Photos/name.png
    - lib/assets/Photos/pic1.png
    - lib/assets/Photos/i2.jpeg
    - lib/assets/Photos/i3.jpeg
    - lib/assets/Photos/abstract-user-flat-3.png
    - assets/audio.mp3
    - assets/audio2.mp3
    - assets/messenger.mp3
    - assets/Pictures/
    - assets/images/
    - assets/images/Artists/
    - assets/languages/

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/Montserrat/Montserrat-Regular.ttf
        - asset: lib/assets/Montserrat/Montserrat-Light.ttf
        - asset: lib/assets/Montserrat/Montserrat-Thin.ttf
    - family: Poppins
      fonts:
        - asset: lib/assets/Poppins/Poppins-Regular.ttf
    - family: Circular
      fonts:
        - asset: lib/assets/CircularSpUIAra-Bold.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
